# Generated by Django 4.0.4 on 2022-04-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField(auto_created=True)),
                ('FullName', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=40)),
                ('State', models.CharField(max_length=40)),
                ('Pincode', models.CharField(max_length=6)),
                ('Gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10)),
                ('Address', models.TextField(max_length=500)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.master')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
