# Generated by Django 4.0.4 on 2022-04-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Address',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='City',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(auto_created=True, default='2022-01-01'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='FullName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Pincode',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='State',
            field=models.CharField(default='', max_length=40),
        ),
    ]
