# Generated by Django 4.0.4 on 2022-04-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0003_alter_profile_address_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ProfileImage',
            field=models.FileField(default='images/user.png', upload_to='images/users'),
        ),
    ]
