# Generated by Django 4.0.4 on 2022-04-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0004_profile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ProfileImage',
            field=models.FileField(default='images/users/customer-5.jpg', upload_to='images/users'),
        ),
    ]
