# Generated by Django 4.0.4 on 2022-05-11 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0007_alter_profile_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodImage', models.FileField(default='images/food.png', upload_to='images/fooditems')),
                ('Name', models.CharField(max_length=50)),
                ('Type', models.CharField(choices=[('veg', 'veg'), ('eg', 'egg'), ('nveg', 'non-veg')], max_length=10)),
                ('Price', models.FloatField()),
                ('Description', models.TextField(max_length=250)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.category')),
            ],
            options={
                'db_table': 'FoodItem',
            },
        ),
        migrations.CreateModel(
            name='UserFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.fooditem')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.profile')),
            ],
            options={
                'db_table': 'UserFavourite',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('TotalPrice', models.FloatField()),
                ('FoodItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.fooditem')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.profile')),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
    ]
